version: '3.8'

services:
  app:
    image: ninja/loginpage
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8031:8031"
    # environment:
    #   NODE_ENV: development
    #   DB_HOST: db
    #   DB_USER: root
    #   DB_PASSWORD: example
    #   DB_NAME: mydatabase
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
