version: '3.8'

services:
  app:
    image: ninja/loginpage
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8031:8031"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
